package POJOs;
// Generated 01-may-2018 18:31:57 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Comentario generated by hbm2java
 */
public class Comentario  implements java.io.Serializable {


     private Integer id;
     private Publicacion publicacion;
     private Usuario usuario;
     private Date fechaHora;
     private String contenido;
     private Set votoComentarios = new HashSet(0);

    public Comentario() {
    }

	
    public Comentario(Publicacion publicacion, Usuario usuario, Date fechaHora, String contenido) {
        this.publicacion = publicacion;
        this.usuario = usuario;
        this.fechaHora = fechaHora;
        this.contenido = contenido;
    }
    public Comentario(Publicacion publicacion, Usuario usuario, Date fechaHora, String contenido, Set votoComentarios) {
       this.publicacion = publicacion;
       this.usuario = usuario;
       this.fechaHora = fechaHora;
       this.contenido = contenido;
       this.votoComentarios = votoComentarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Publicacion getPublicacion() {
        return this.publicacion;
    }
    
    public void setPublicacion(Publicacion publicacion) {
        this.publicacion = publicacion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public Set getVotoComentarios() {
        return this.votoComentarios;
    }
    
    public void setVotoComentarios(Set votoComentarios) {
        this.votoComentarios = votoComentarios;
    }




}


