package POJOs;
// Generated 01-may-2018 18:31:57 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Mensaje generated by hbm2java
 */
public class Mensaje  implements java.io.Serializable {


     private Integer id;
     private Chat chat;
     private Usuario usuario;
     private String contenido;
     private Date fechaHora;
     private boolean estado;

    public Mensaje() {
    }

    public Mensaje(Chat chat, Usuario usuario, String contenido, Date fechaHora, boolean estado) {
       this.chat = chat;
       this.usuario = usuario;
       this.contenido = contenido;
       this.fechaHora = fechaHora;
       this.estado = estado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Chat getChat() {
        return this.chat;
    }
    
    public void setChat(Chat chat) {
        this.chat = chat;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


