package POJOs;
// Generated 01-may-2018 18:31:57 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Publicacion generated by hbm2java
 */
public class Publicacion  implements java.io.Serializable {


     private Integer id;
     private Tematica tematica;
     private Usuario usuario;
     private String titulo;
     private String contenido;
     private Date fechaHoraCreacion;
     private Date fechaHoraModificacion;
     private String ruta;
     private Set votoPublicacions = new HashSet(0);
     private Set comentarios = new HashSet(0);
     private Set suscripcions = new HashSet(0);

    public Publicacion() {
    }

	
    public Publicacion(Tematica tematica, Usuario usuario, String titulo, String contenido, Date fechaHoraCreacion, Date fechaHoraModificacion, String ruta) {
        this.tematica = tematica;
        this.usuario = usuario;
        this.titulo = titulo;
        this.contenido = contenido;
        this.fechaHoraCreacion = fechaHoraCreacion;
        this.fechaHoraModificacion = fechaHoraModificacion;
        this.ruta = ruta;
    }
    public Publicacion(Tematica tematica, Usuario usuario, String titulo, String contenido, Date fechaHoraCreacion, Date fechaHoraModificacion, String ruta, Set votoPublicacions, Set comentarios, Set suscripcions) {
       this.tematica = tematica;
       this.usuario = usuario;
       this.titulo = titulo;
       this.contenido = contenido;
       this.fechaHoraCreacion = fechaHoraCreacion;
       this.fechaHoraModificacion = fechaHoraModificacion;
       this.ruta = ruta;
       this.votoPublicacions = votoPublicacions;
       this.comentarios = comentarios;
       this.suscripcions = suscripcions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tematica getTematica() {
        return this.tematica;
    }
    
    public void setTematica(Tematica tematica) {
        this.tematica = tematica;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public Date getFechaHoraCreacion() {
        return this.fechaHoraCreacion;
    }
    
    public void setFechaHoraCreacion(Date fechaHoraCreacion) {
        this.fechaHoraCreacion = fechaHoraCreacion;
    }
    public Date getFechaHoraModificacion() {
        return this.fechaHoraModificacion;
    }
    
    public void setFechaHoraModificacion(Date fechaHoraModificacion) {
        this.fechaHoraModificacion = fechaHoraModificacion;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }
    public Set getVotoPublicacions() {
        return this.votoPublicacions;
    }
    
    public void setVotoPublicacions(Set votoPublicacions) {
        this.votoPublicacions = votoPublicacions;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }
    public Set getSuscripcions() {
        return this.suscripcions;
    }
    
    public void setSuscripcions(Set suscripcions) {
        this.suscripcions = suscripcions;
    }




}


