package POJOs;
// Generated 01-may-2018 18:31:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tematica generated by hbm2java
 */
public class Tematica  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String imagen;
     private Set publicacions = new HashSet(0);

    public Tematica() {
    }

	
    public Tematica(String nombre, String imagen) {
        this.nombre = nombre;
        this.imagen = imagen;
    }
    public Tematica(String nombre, String imagen, Set publicacions) {
       this.nombre = nombre;
       this.imagen = imagen;
       this.publicacions = publicacions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public Set getPublicacions() {
        return this.publicacions;
    }
    
    public void setPublicacions(Set publicacions) {
        this.publicacions = publicacions;
    }




}


