package POJOs;
// Generated 01-may-2018 18:31:57 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apellidos;
     private String nickname;
     private String password;
     private String email;
     private boolean tipo;
     private Date fechaNacimiento;
     private Set chats = new HashSet(0);
     private Set suscripcions = new HashSet(0);
     private Set votoPublicacions = new HashSet(0);
     private Set comentarios = new HashSet(0);
     private Set mensajes = new HashSet(0);
     private Set votoComentarios = new HashSet(0);
     private Set publicacions = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String nombre, String apellidos, String nickname, String password, String email, boolean tipo, Date fechaNacimiento) {
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.nickname = nickname;
        this.password = password;
        this.email = email;
        this.tipo = tipo;
        this.fechaNacimiento = fechaNacimiento;
    }
    public Usuario(String nombre, String apellidos, String nickname, String password, String email, boolean tipo, Date fechaNacimiento, Set chats, Set suscripcions, Set votoPublicacions, Set comentarios, Set mensajes, Set votoComentarios, Set publicacions) {
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.nickname = nickname;
       this.password = password;
       this.email = email;
       this.tipo = tipo;
       this.fechaNacimiento = fechaNacimiento;
       this.chats = chats;
       this.suscripcions = suscripcions;
       this.votoPublicacions = votoPublicacions;
       this.comentarios = comentarios;
       this.mensajes = mensajes;
       this.votoComentarios = votoComentarios;
       this.publicacions = publicacions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public boolean isTipo() {
        return this.tipo;
    }
    
    public void setTipo(boolean tipo) {
        this.tipo = tipo;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Set getChats() {
        return this.chats;
    }
    
    public void setChats(Set chats) {
        this.chats = chats;
    }
    public Set getSuscripcions() {
        return this.suscripcions;
    }
    
    public void setSuscripcions(Set suscripcions) {
        this.suscripcions = suscripcions;
    }
    public Set getVotoPublicacions() {
        return this.votoPublicacions;
    }
    
    public void setVotoPublicacions(Set votoPublicacions) {
        this.votoPublicacions = votoPublicacions;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }
    public Set getMensajes() {
        return this.mensajes;
    }
    
    public void setMensajes(Set mensajes) {
        this.mensajes = mensajes;
    }
    public Set getVotoComentarios() {
        return this.votoComentarios;
    }
    
    public void setVotoComentarios(Set votoComentarios) {
        this.votoComentarios = votoComentarios;
    }
    public Set getPublicacions() {
        return this.publicacions;
    }
    
    public void setPublicacions(Set publicacions) {
        this.publicacions = publicacions;
    }




}


