package POJOs;
// Generated 01-may-2018 18:31:57 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VotoPublicacion generated by hbm2java
 */
public class VotoPublicacion  implements java.io.Serializable {


     private Integer id;
     private Publicacion publicacion;
     private Usuario usuario;
     private boolean tipo;
     private Date fechaHora;

    public VotoPublicacion() {
    }

    public VotoPublicacion(Publicacion publicacion, Usuario usuario, boolean tipo, Date fechaHora) {
       this.publicacion = publicacion;
       this.usuario = usuario;
       this.tipo = tipo;
       this.fechaHora = fechaHora;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Publicacion getPublicacion() {
        return this.publicacion;
    }
    
    public void setPublicacion(Publicacion publicacion) {
        this.publicacion = publicacion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public boolean isTipo() {
        return this.tipo;
    }
    
    public void setTipo(boolean tipo) {
        this.tipo = tipo;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }




}


